version: '2.1'
services:
  kosmtik:
    image: kosmtik:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/cyclosm
    # todo: get ssl working?
    #  - ./ssl:/ssl
    # command: kosmtik serve --host 0.0.0.0 --port 6789 --ssl-cert /ssl/cert.pem --ssl-key /ssl/key.pem
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGUSER=postgres
    # BEGIN: Add SSL configuration
    ports:
      - "0.0.0.0:6789:6789"
      # ssl?
      # - "0.0.0.0:443:443"
  db:
    image: db:v1
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - PG_WORK_MEM
      - PG_MAINTENANCE_WORK_MEM
  import:
    image: import:v1
    build:
      context: .
      dockerfile: Dockerfile.import
    volumes:
      - .:/cyclosm
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PG_WORK_MEM
      - PG_MAINTENANCE_WORK_MEM
      - OSM2PGSQL_CACHE
      - OSM2PGSQL_NUMPROC
      - OSM2PGSQL_DATAFILE
